In [112]:
import pandas as pd 
import numpy as np

In [113]:
dftrain=pd.read_csv("train.csv")

In [114]:
dftest=pd.read_csv("test.csv")

In [115]:
dftrain.head()

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f276,f277,f278,f279,f280,f281,f282,f283,f284,target
0,0,0.205979,0.410993,0.176775,0.223581,0.423543,0.476140,0.413590,0.612021,0.534873,...,0,1,0,0,0,0,0,0,0,1
1,1,0.181004,0.473119,0.011734,0.213657,0.619678,0.441593,0.230407,0.686013,0.281971,...,0,1,0,0,0,0,0,0,0,1
2,2,0.182583,0.307431,0.325950,0.207116,0.605699,0.309695,0.493337,0.751107,0.536272,...,0,0,0,1,1,0,0,0,0,1
3,3,0.180240,0.494592,0.008367,0.223580,0.760618,0.439211,0.432055,0.776147,0.483958,...,0,0,0,0,1,0,0,0,0,1
4,4,0.177172,0.495513,0.014263,0.548819,0.625396,0.562493,0.117158,0.561255,0.077115,...,0,1,1,0,1,0,0,1,0,1

In [116]:
dftrain.shape

(1000000, 287)

In [117]:
dftrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 287 entries, id to target
dtypes: float64(240), int64(47)
memory usage: 2.1 GB

In [118]:
dftrain.isnull().sum()

id        0
f0        0
f1        0
f2        0
f3        0
         ..
f281      0
f282      0
f283      0
f284      0
target    0
Length: 287, dtype: int64

In [119]:
dftrain.describe()

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f276,f277,f278,f279,f280,f281,f282,f283,f284,target
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000
mean,499999.500000,0.214334,0.460218,0.129253,0.277598,0.580710,0.416619,0.386532,0.654858,0.462256,...,0.250096,0.137164,0.144793,0.130667,0.139210,0.199331,0.156065,0.183741,0.15468,0.500485
std,288675.278933,0.053320,0.101316,0.120805,0.063163,0.115338,0.058231,0.133457,0.065158,0.129439,...,0.433068,0.344021,0.351892,0.337036,0.346166,0.399498,0.362917,0.387273,0.36160,0.500000
min,0.000000,0.041790,0.022016,0.000381,0.000000,0.000000,0.000959,0.000592,0.017994,0.000990,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,249999.750000,0.181676,0.389215,0.017692,0.235342,0.497938,0.374390,0.317815,0.615372,0.363753,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,499999.500000,0.204498,0.453893,0.095496,0.264669,0.565059,0.414009,0.420260,0.648562,0.475701,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000
75%,749999.250000,0.229684,0.526023,0.177717,0.305837,0.657024,0.458360,0.477140,0.692666,0.561372,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000
max,999999.000000,1.000000,0.959019,0.994818,0.979797,1.000000,0.907889,0.972601,0.986195,0.986118,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [120]:
Y=dftrain['target']

In [121]:
dftrain.drop('target',inplace=True,axis=1)

In [122]:
dftrain.drop("id",inplace=True,axis=1)

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(dftrain, Y, test_size=0.00000001,random_state=0)

In [124]:
from sklearn.preprocessing import StandardScaler

In [ ]:
#StandardScaler
sc2=StandardScaler()
sc2.fit(X_train)
X_train2=sc2.transform(X_train)
X_test2=sc2.transform(X_test)
Y_train2=Y_train
Y_test2=Y_test

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rn=RandomForestClassifier(max_depth=2, random_state=0)

In [ ]:
 rn.fit(X_train2,Y_train2)

In [ ]:
 sgc=SGDClassifier(max_iter=100000, tol=1e-5)

In [65]:
sgc.fit(X_train2,Y_train2)

SGDClassifier(max_iter=100000, tol=1e-05)

In [66]:
sgc.score(X_test2,Y_test2)

0.0

In [67]:
dftest

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f275,f276,f277,f278,f279,f280,f281,f282,f283,f284
0,1000000,0.178216,0.435617,0.010230,0.202074,0.390170,0.324221,0.221722,0.738894,0.582588,...,1,0,0,0,0,0,1,1,1,0
1,1000001,0.181250,0.476455,0.022413,0.283146,0.598020,0.349508,0.283467,0.721575,0.268990,...,0,0,0,0,0,0,0,0,0,0
2,1000002,0.159721,0.451202,0.259649,0.365274,0.594634,0.413502,0.249318,0.642339,0.411104,...,0,0,0,0,0,0,1,0,0,0
3,1000003,0.182424,0.520976,0.095344,0.327742,0.741830,0.358711,0.270077,0.601662,0.297742,...,0,0,0,0,0,1,1,0,0,0
4,1000004,0.229329,0.336513,0.023511,0.300913,0.668738,0.481586,0.545660,0.667849,0.546045,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,1499995,0.185473,0.525338,0.014945,0.204029,0.498957,0.431933,0.470553,0.731268,0.452134,...,1,0,0,0,0,0,1,0,0,0
499996,1499996,0.183194,0.553266,0.008055,0.280651,0.636591,0.478092,0.450386,0.582647,0.517270,...,1,0,0,0,0,0,0,1,0,0
499997,1499997,0.184650,0.533643,0.011218,0.201262,0.720698,0.472888,0.427469,0.589259,0.243879,...,1,1,0,0,0,0,0,0,0,0
499998,1499998,0.227731,0.513247,0.178603,0.313778,0.665656,0.401365,0.183369,0.708233,0.575135,...,0,0,0,0,0,0,1,0,0,0
499999,1499999,0.185561,0.406225,0.097598,0.327129,0.655168,0.384097,0.330797,0.747355,0.409955,...,1,0,0,0,0,1,0,0,0,0

In [ ]:
dftest1=dftest
df=dftest1[['id']]
dftest1.drop('id',inplace=True, axis=1)

In [ ]:
X=dftest1.to_numpy()

In [ ]:
sc=StandardScaler()
sc.fit(X)

In [ ]:
xpredict=sc.transform(X)

In [ ]:
ypredict=rn.predict(xpredict)

In [ ]:
ypredict.shape

In [ ]:
df['target']=ypredict

In [ ]:
df

In [ ]:
df.to_csv('file.csv', header=True, index=False)